### PR TITLE
chore: add countly integration

### PR DESCRIPTION
**Pull request by zebateira**
This PR updates the countly integration to not load countly through a remote url, instead it uses the package [countly-sdk-web](https://www.npmjs.com/package/countly-sdk-web).

The app key and the server url are directly configured in Fleek.
In order to also avoid creating new DNS links to countly for each project and have the Countly Team generate new certificates, we could simply have one single countly link that is used for the whole org (I'm requesting this ATM to see if it makes sense). This simplifies the countly integration flow. When this is done, we can simply update the countly server url in Fleek and re-deploy.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by zebateira** [comment]
@johndmulhausen also did more renaming that I think we missed in the ci check scripts?

**Comment by filecorgi** [comment]
@zebateira The CI scripts are pretty geared towards content checks so the renames would have to touch .md files for Filecorgi to catch it. Although it also does check for build failure.

**Review by filecorgi — APPROVED** [review]
LGTM :)

**Review by johndmulhausen — APPROVED** [review]
LGTM :)

**Comment by zebateira** [comment]
I thought @filecorgi had evolved 😂

**Pull request merged**
