### PR TITLE
fixes for how-to testing feedback

### PR DESCRIPTION
**Pull request by yusefnapora**
This is a wip PR to address things that shake out of the how-to testing that @johnnymatthews & @terichadbourne are up to in https://github.com/web3-storage/docs/issues/82. Feel free to push commits here if you see anything with an obvious fix - I'll be tied up for the next few hours but will circle back this afternoon.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can see more worldwide...
                                             ^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...uy7pcu, you can make a URL for the dweb.link gateway as follows: bafybeidd2g...
                                             ^^^^
  ```
- Use ‘own’ only if you want to emphasize that something belongs to a person or thing or was done by a person or thing. Consider writing “your”.
  ```
  ... so if you're looking to link to one of your own files, you don't even have ...
                                             ^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...t up and running in just a few minutes. First you'll need to add the web3.st...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.
  ```
  ...S data: files and unixFsIterator(). The files method returns an array of Web...
                                             ^^^^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- Possibly missing comma found.
  ```
  ...ent to <FILE NAME>. Desktop/output-file.txt Your complete command should loo...
                                             ^^^
  ```
- The verb “check out” can sound colloquial in this context. Consider using a more formal alternative.
  ```
  ...h how to store data using Web3.Storage, check out the storage how-to guide f...
                                             ^^^^^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.
  ```
  ... can also use the client library to get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can see more worldwide...
                                             ^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...uy7pcu, you can make a URL for the dweb.link gateway as follows: bafybeidd2g...
                                             ^^^^
  ```
- Use ‘own’ only if you want to emphasize that something belongs to a person or thing or was done by a person or thing. Consider writing “your”.
  ```
  ... so if you're looking to link to one of your own files, you don't even have ...
                                             ^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...t up and running in just a few minutes. First you'll need to add the web3.st...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.
  ```
  ...S data: files and unixFsIterator(). The files method returns an array of Web...
                                             ^^^^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- Possibly missing comma found.
  ```
  ...ent to <FILE NAME>. Desktop/output-file.txt Your complete command should loo...
                                             ^^^
  ```
- The verb “check out” can sound colloquial in this context. Consider using a more formal alternative.
  ```
  ...h how to store data using Web3.Storage, check out the storage how-to guide f...
                                             ^^^^^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.
  ```
  ... can also use the client library to get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```
### `docs/how-tos/store.md`:
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...s such as fetch  (opens new window) and File  (opens new window). This guide...
                                             ^^^^
  ```
- Possibly missing comma found.
  ```
  ....storage package to your dependencies:  First we need to create a Web3.Stora...
                                             ^^^^^
  ```
- The phrase ‘a lot of’ might be wordy. Consider using “many”.
  ```
  ...ent method: If you expect to be loading a lot of large files, you may be bet...
                                             ^^^^^^^^
  ```
- Apostrophe might be missing. Did you mean “file’s” (curly possessive apostrophe) or “file's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)
  ```
  ...one content archive, and linking to the files inside is much easier if each ...
                                             ^^^^^
  ```
- Possibly missing comma found.
  ```
  ...an array of Files, uploading is simple: IMPORTANT Deleting files from the We...
                                             ^^^^^^^^^
  ```
- Possibly missing article found.
  ```
  ... IMPORTANT Deleting files from the Web3.Storage site's Files page  (opens ne...
                                             ^^^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.
  ```
  ...to guide on retrieval. You can also get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```

**Comment by yusefnapora** [comment]
@johnnymatthews when you get a chance, will you try the `retrieveFiles` from the last commit on this branch? I added some logs to see if we can figure out why it's failing. The error is a bit misleading, since I am actually checking `ok` before we call `.files`.

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can see more worldwide...
                                             ^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...uy7pcu, you can make a URL for the dweb.link gateway as follows: bafybeidd2g...
                                             ^^^^
  ```
- Use ‘own’ only if you want to emphasize that something belongs to a person or thing or was done by a person or thing. Consider writing “your”.
  ```
  ... so if you're looking to link to one of your own files, you don't even have ...
                                             ^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...t up and running in just a few minutes. First you'll need to add the web3.st...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.
  ```
  ...S data: files and unixFsIterator(). The files method returns an array of Web...
                                             ^^^^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- Possibly missing comma found.
  ```
  ...ent to <FILE NAME>. Desktop/output-file.txt Your complete command should loo...
                                             ^^^
  ```
- The verb “check out” can sound colloquial in this context. Consider using a more formal alternative.
  ```
  ...h how to store data using Web3.Storage, check out the storage how-to guide f...
                                             ^^^^^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.
  ```
  ... can also use the client library to get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```
### `docs/how-tos/store.md`:
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...s such as fetch  (opens new window) and File  (opens new window). This guide...
                                             ^^^^
  ```
- Possibly missing comma found.
  ```
  ....storage package to your dependencies:  First we need to create a Web3.Stora...
                                             ^^^^^
  ```
- The phrase ‘a lot of’ might be wordy. Consider using “many”.
  ```
  ...ent method: If you expect to be loading a lot of large files, you may be bet...
                                             ^^^^^^^^
  ```
- Apostrophe might be missing. Did you mean “file’s” (curly possessive apostrophe) or “file's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)
  ```
  ...one content archive, and linking to the files inside is much easier if each ...
                                             ^^^^^
  ```
- Possibly missing comma found.
  ```
  ...an array of Files, uploading is simple: IMPORTANT Deleting files from the We...
                                             ^^^^^^^^^
  ```
- Possibly missing article found.
  ```
  ... IMPORTANT Deleting files from the Web3.Storage site's Files page  (opens ne...
                                             ^^^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.
  ```
  ...to guide on retrieval. You can also get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```

**Review by johnnymatthews — APPROVED** [review]
Oh yeah, that's the stuff!

**Pull request merged**
