### PR TITLE
Restyle blockquotes as callouts

### PR DESCRIPTION
**Pull request by jessicaschilling**
This PR addresses @johnnymatthews' idea from https://github.com/web3-storage/docs/pull/35 by repurposing `<blockquote>` as something more visually similar to a callout. This means we can still use ordinary Markdown syntax without injecting any html.

image

image

### CODE REVIEW

**Comment by yusefnapora** [comment]
Oh nice, this looks great!

**Review by johnnymatthews — APPROVED** [review]
This looks great!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Review by zebateira — APPROVED** [review]
Good job 👏

**Pull request merged**
