### PR TITLE
Adds a bunch of horrible colours onto the page.

### PR DESCRIPTION
**Pull request by johnnymatthews**
Trying to make the introduction paragraph stand out a teeny bit. Dunno if I've achieved that. I can't front-end...

image

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by jessicaschilling** [comment]
@johnnymatthews I'll need to find a way to do this that doesn't bork screen-readers by inferring things with the header hierarchy.

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by johnnymatthews** [comment]
Gonna close this PR since it's not needed.

**Pull request closed without merging**
