### PR TITLE
feat: add nft storage banner

### LINKED ISSUE #67: Implement banner directing to nft.storage
Please match the banner now found at https://staging.web3.storage/

image

### PR DESCRIPTION
**Pull request by zebateira**
Closes #67

Would appreciate some eyes on this since I had to play around Vuepress' default theme a little bit. I tested on mobile and other browsers.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Review by jessicaschilling — CHANGES_REQUESTED** [review]
Thank you! Could you please reduce the line height at narrow breakpoints so it doesn't wrap awkwardly on very small phones?

image

**Comment by zebateira** [comment]
image

How about that?

**Comment by jessicaschilling** [comment]
Beautiful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by terichadbourne** [comment]
Looks great, thanks! Merging now.

**Pull request merged**
