### PR TITLE
feat(concepts): add web3.storage economics concept article

### LINKED ISSUE #169: Explain "how is this free"
Related to the discussion mentioned in #168, a lot of users and potential users are likely to wonder how the service can manage to be free.

We should explain the high-level premise of Filecoin+ / DataCap leading to greater block rewards and how that makes free long-term storage viable. Will likely need input on the exact messaging, etc to use here.

### PR DESCRIPTION
**Pull request by yusefnapora**
This adds a "Web3.Storage economics" concept article, which is mostly a copy / paste job from the [Intro blog post](https://filecoin.io/blog/posts/introducing-web3-storage/) with a few light edits.

Closes #169 

@dchoi27 does this go into enough detail? For a minute I was tempted to go into the weeds about Filecoin Plus a bit, but I think linking out might be the best balance of giving info to the curious without overwhelming people who don't care.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/storage-economics.md`:
- If this is a compound adjective that modifies the following noun, use a hyphen.
  ```
  ...ards for doing so. This translates into real world profits for storage provi...
                                             ^^^^^^^^^^
  ```
- Consider a shorter alternative to avoid wordiness.
  ```
  ...fer free storage and retrieval services in order to get this block reward mu...
                                             ^^^^^^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/storage-economics.md`:
- Consider a shorter alternative to avoid wordiness.
  ```
  ...fer free storage and retrieval services in order to get this block reward mu...
                                             ^^^^^^^^^^^
  ```

**Comment by dchoi27** [comment]
LGTM! Adding @atopal as a reviewer as well (since this will need to be coordinated with homepage copy changes)

**Review by dchoi27 — APPROVED** [review]

**Comment by atopal** [comment]
Let's ship this!

**Review by atopal — APPROVED** [review]
Let's ship this!

**Pull request merged**
