### PR TITLE
feat: add Algolia config

### PR DESCRIPTION
**Pull request by jessicaschilling**
This PR adds config for Algolia search, pending approval of an open-source plan. **Please don't merge yet.**
Closes https://github.com/web3-storage/docs/issues/62.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by jessicaschilling** [comment]
This isn't working for some reason - I've opened an Algolia support ticket and will update anything I learn here.

Known so far:
- The `apiKey` and `indexName` in this PR are correct, as confirmed in the Algolia user dashboard
- There doesn't seem to be anything wrong with the PR code itself; this usage is a direct clone of how we have things set up in IPFS docs, just using the different `apiKey` and `indexName`.
- If I plug in the IPFS Docs `apiKey` and `indexName` on a local build, the search box works ... but of course searches the data from IPFS docs.
- Keeping that in mind, it suggests there's something amiss in the Algolia setup itself.

cc @johnnymatthews @atopal

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by yusefnapora** [comment]
I did some poking at this today, and discovered that I can manually update the search index by running the `docsearch` scraper as described [here](https://docsearch.algolia.com/docs/run-your-own). Then, if you set a custom `appId` in the algolia vuepress config, it finds and uses the index:

Screen Shot 2021-09-13 at 1 55 55 PM


So it looks like Algolia created an index for us, but didn't add us to the main docsearch scraper config. I'm not sure what the deal with that is, but it's pretty simple to just run the scraper ourselves, so I added a GitHub cron action to run it every 24 hours.

One nice thing about running it ourselves is that we aren't dependent on Algolia pulling in config changes if we change the site structure, e.g. when porting to docusaurus. We can just update the local algolia config and regenerate the index ourselves.

I haven't tested the action yet, but I figure we can merge this and keep an eye out for any failures.

**Pull request merged**
