### PR TITLE
fix: new tabs components styles

### PR DESCRIPTION
**Pull request by zebateira**
Fixes styling of the new tabs component.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by johnnymatthews** [comment]
Lovely stuff

image

**Review by johnnymatthews — APPROVED** [review]

**Comment by johnnymatthews** [comment]
The anchor links seem to act a bit weird. Is it possible to keep the screen where it is when changing tabs? Happens on Brave and Firefox.

https://user-images.githubusercontent.com/9611008/126682239-f49b11da-93b5-41ad-bd62-d938deedbeb0.mp4

**Review by jessicaschilling — APPROVED** [review]
Thanks so much for doing this!
@zebateira - do you mind addressing @johnnymatthews' comment? Otherwise this is great.

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by zebateira** [comment]
It's not possible to stop the auto scroll to the content, but I added a bit of margin so the header doesn't cover part of it.
Does this look better?

https://user-images.githubusercontent.com/2353186/126764490-dd24e638-a303-4646-8ba5-f41ab92104f9.mp4

You still get the initial scroll to content (desirable so the amazing linking works), but then the tabs and the content are fully visible to interact with.

**Comment by johnnymatthews** [comment]
That works for me @zebateira! Cheers for that! Merging.

**Pull request merged**
