### PR TITLE
Use complete functions in how-to examples

### LINKED ISSUE #95: how-to: add context to examples for easier copy/paste, etc
On review, several of the how-to examples assume knowledge of things like "you need to be inside of an `async` function to `await` things".

Things we can do to make the how-to more accessible and easier to copy/paste from:

- [x] make all uses of `await` occur inside of an `async` function
- [x] wrap the client creation code in a function, so we can refer to it elsewhere on the page
- [ ] maybe: link to some intro to async / await material for new js devs
- [x] bonus: write up the how-to code as a real example and pull in snippets with vuepress voodoo

### PR DESCRIPTION
**Pull request by yusefnapora**
This is an attempt to make the how-to guides more copy/paste friendly by making sure all `await` statements are contained in an `async function`. That should hopefully help people who are new to `async`/`await` and might otherwise try to paste into a non-async function.

I also refactored things a bit so we're pulling snippets from files in `/code-snippets/how-to` instead of keeping the code inline with the markdown. It should be possible to write a little smoke test to sanity check things, but that can wait until things settle down. At least you can use a real IDE to edit the example code, which is nice. Also, using snippets let me re-use the same boilerplate (importing, making a new client, etc) for all the how-to guides, which seems like a win.

Closes #95

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/how-tos/query.md`:
- Possibly missing preposition found.
  ```
  ... files. When you store a file with Web3.Storage, you receive a content ident...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...re's how to include it in your project: IMPORTANT Remember to check the retu...
                                             ^^^^^^^^^
  ```
- Possibly missing preposition found.
  ```
  ... is valid and has been uploaded to Web3.Storage, the status method will retu...
                                             ^^^^^^^
  ```
- Possible agreement error.
  ```
  ...an the total size of the files on disk. pins contains an array of objects de...
                                             ^^^^^^^^^^^^^
  ```
- Possible agreement error.
  ```
  ... fast retrieval using the IPFS network. deals contains an array of objects d...
                                             ^^^^^^^^^^^^^^
  ```
- The verb “check out” can sound colloquial in this context. Consider using a more formal alternative.
  ```
  ...h how to store data using Web3.Storage, check out the storage how-to guide f...
                                             ^^^^^^^^^
  ```
- Check of `docs/how-tos/regenerate-api-token.md` came back clean!
### `docs/how-tos/retrieve.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.
  ```
  ...S data: files and unixFsIterator(). The files method returns an array of Web...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can see more worldwide...
                                             ^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...uy7pcu, you can make a URL for the dweb.link gateway as follows: bafybeidd2g...
                                             ^^^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- Possibly missing comma found.
  ```
  ...ent to <FILE NAME>. Desktop/output-file.txt Your complete command should loo...
                                             ^^^
  ```
- The verb “check out” can sound colloquial in this context. Consider using a more formal alternative.
  ```
  ...h how to store data using Web3.Storage, check out the storage how-to guide f...
                                             ^^^^^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.
  ```
  ... can also use the client library to get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```

### `docs/reference/client-library.md`:
- Possibly missing preposition found.
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- ‘your’ (possessive pronoun) seems less likely than ‘you’ (personal pronoun).
  ```
  ...ties that can be used as parameters for your put() operation: name String. T...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...rameters for your put() operation: name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)
  ```
  ...ens new window) format. pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```

**Review by jessicaschilling — APPROVED** [review]
LGTM!

**Comment by terichadbourne** [comment]
I think it makes sense for me to skip reviewing now since I'll be testing the same content tomorrow. Would suggest we merge and then get feedback on the how to examples once live. Does that feel okay to you @yusefnapora or do you have specific concerns you'd like a tech review on first?

**Comment by terichadbourne** [comment]
Merging this one with @yusefnapora's go-ahead for the sake of expediency, but a review from Spark in the updated live how tos would still be appreciated.

**Pull request merged**
