### PR TITLE
Style: update nav so clickable headers match formatting

### PR DESCRIPTION
**Pull request by jessicaschilling**
This PR addresses the issue raised by @jnthnvctr of left-nav headers with links not displaying in the same manner as non-link headers — however, it's not very tidy. @zebateira, do you have the bandwidth to have a look? 🙏

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by zebateira** [comment]
@jessicaschilling done. just a small tweak.

**Review by zebateira — APPROVED** [review]
All good 👏 🚀

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Pull request merged**
